#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
gpu_ids: [0,1,2,3]

sde:
  max_sigma: 25
  T: 1000
  schedule: cosine # cosine # linear

degradation: # for val set
  sigma: 25
  noise_type: G # Gaussian noise: G
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: GT
    dataroot_GT: /p/scratch/delia-mp/lin4/RestormerGrayScaleData/clean/train/DFWB

    use_shuffle: true
    n_workers: 8 # per GPU, correspond to nubmer of cores on GPU
    batch_size: 16 # effective batch size, should be a factor of # GPUs
    GT_size: 128
    use_flip: true
    use_rot: true
    color: gray
    #data_type: img, default but wouldn't affect input bmp data, the author use SwinIR dataset to train
  
  val:
    name: Test_Dataset
    mode: GT
    dataroot_GT: /p/scratch/delia-mp/lin4/RestormerGrayScaleData/clean/test/BSD68

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

#### path
path:
  root: /p/scratch/delia-mp/lin4/experiment_result/irsde/0804-gaussian-25
  pretrain_model_G: ~
  strict_load: true
  resume_state: /p/scratch/delia-mp/lin4/experiment_result/irsde/0804-gaussian-25/experiments/denoising-sde/ir-sde/training_state/297000.state

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000 
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-6

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e4
  

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: 3000
  