#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
distortion: rician
gpu_ids: [0,1,2,3]

sde:
  T: 1000
  max_sigma: 10 # won't change
  schedule: cosine # linear, cosine
  eps: 0.005 # since it's SDE


degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 50 # no use
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 1 # no use
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /p/scratch/delia-mp/lin4/RestormerGrayScaleData/clean/train/DFWB
    dataroot_LQ: /p/scratch/delia-mp/lin4/RestormerGrayScaleData/rician_noise_50/train/DFWB

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    GT_size: 128
    LR_size: 128
    use_flip: true
    use_rot: true
    color: gray

  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /p/scratch/delia-mp/lin4/RestormerGrayScaleData/clean/test/BSD68
    dataroot_LQ: /p/scratch/delia-mp/lin4/RestormerGrayScaleData/rician_noise_50/test/BSD68

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

#### path
path:
  # log dir
  root: /p/scratch/delia-mp/lin4/experiment_result/irsde/0804-rician-50
  pretrain_model_G: ~
  strict_load: true
  resume_state: /p/scratch/delia-mp/lin4/experiment_result/irsde/0804-rician-50/experiments/deraining/ir-sde/training_state/24000.state

#### training settings: learning rate scheme, loss
train:
  manual_seed: 0
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 300000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e4

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: 3000
